# Generated by Django 5.2.5 on 2025-08-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_navlink_sitelogo_sitesettings_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banners/videos/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/images/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
