# Generated by Django 5.2 on 2025-08-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='date_subscribed',
            new_name='subscribed_at',
        ),
    ]
