# Generated by Django 5.2 on 2025-08-16 09:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_date_subscribed_newslettersubscriber_subscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
