# Generated by Django 5.2 on 2025-08-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_newslettersubscriber_subscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('standard', 'Standard Delivery (3-5 Days)'), ('express', 'Express Delivery (1-2 Days)'), ('pickup', 'Store Pickup')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.CharField(choices=[('blue_dart', 'Blue Dart'), ('shiprocket', 'Shiprocket')], default='blue_dart', max_length=20),
        ),
    ]
