# Generated by Django 5.2 on 2025-08-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_delivery_option_order_delivery_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_partner',
            field=models.CharField(choices=[('Blue Dart', 'Blue Dart'), ('Shiprocket', 'Shiprocket')], default='Blue Dart', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order'),
        ),
    ]
