# Generated by Django 5.2 on 2025-09-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelogo',
            name='alt_text',
            field=models.CharField(default='TechMart Logo', max_length=50),
        ),
    ]
