# Generated by Django 5.2 on 2025-09-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_sitelogo_alt_text'),
    ]

    operations = [
    ]
